---
- name: Update apt cache
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Ping internet
      ansible.builtin.shell: ping -c 4 4.2.2.2
